# This yaml file is used to run the database before running the application for testing
version: '3'

services:

  mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume: